const fs = require('fs');
const path = require('path');

const a1Words = [
  { term: 'a, an', pos: 'indefinite article', def: 'một', us: '/ə/, /æn/', uk: '/ə/, /æn/' },
  { term: 'about', pos: 'prep., adv.', def: 'về, khoảng', us: '/əˈbaʊt/', uk: '/əˈbaʊt/' },
  { term: 'above', pos: 'prep., adv.', def: 'ở trên, phía trên', us: '/əˈbʌv/', uk: '/əˈbʌv/' },
  { term: 'across', pos: 'prep., adv.', def: 'băng qua, qua', us: '/əˈkrɔːs/', uk: '/əˈkrɒs/' },
  { term: 'action', pos: 'n.', def: 'hành động', us: '/ˈækʃn/', uk: '/ˈækʃn/' },
  { term: 'activity', pos: 'n.', def: 'hoạt động', us: '/ækˈtɪvəti/', uk: '/ækˈtɪvəti/' },
  { term: 'actor', pos: 'n.', def: 'nam diễn viên', us: '/ˈæktər/', uk: '/ˈæktə(r)/' },
  { term: 'actress', pos: 'n.', def: 'nữ diễn viên', us: '/ˈæktrəs/', uk: '/ˈæktrəs/' },
  { term: 'add', pos: 'v.', def: 'thêm vào, cộng', us: '/æd/', uk: '/æd/' },
  { term: 'address', pos: 'n.', def: 'địa chỉ', us: '/ˈædres/', uk: '/əˈdres/' },
  { term: 'adult', pos: 'n.', def: 'người trưởng thành', us: '/əˈdʌlt/', uk: '/ˈædʌlt/' },
  { term: 'afraid', pos: 'adj.', def: 'sợ hãi, lo sợ', us: '/əˈfreɪd/', uk: '/əˈfreɪd/' },
  { term: 'after', pos: 'prep.', def: 'sau, sau khi', us: '/ˈæftər/', uk: '/ˈɑːftə(r)/' },
  { term: 'afternoon', pos: 'n.', def: 'buổi chiều', us: '/ˌæftərˈnuːn/', uk: '/ˌɑːftəˈnuːn/' },
  { term: 'again', pos: 'adv.', def: 'lại, một lần nữa', us: '/əˈɡen/', uk: '/əˈɡen/' },
  { term: 'age', pos: 'n.', def: 'tuổi, tuổi tác', us: '/eɪdʒ/', uk: '/eɪdʒ/' },
  { term: 'ago', pos: 'adv.', def: 'trước đây, cách đây', us: '/əˈɡoʊ/', uk: '/əˈɡəʊ/' },
  { term: 'agree', pos: 'v.', def: 'đồng ý', us: '/əˈɡriː/', uk: '/əˈɡriː/' },
  { term: 'air', pos: 'n.', def: 'không khí', us: '/er/', uk: '/eə(r)/' },
  { term: 'airport', pos: 'n.', def: 'sân bay', us: '/ˈerpɔːrt/', uk: '/ˈeəpɔːt/' },
  { term: 'all', pos: 'det., pron.', def: 'tất cả', us: '/ɔːl/', uk: '/ɔːl/' },
  { term: 'also', pos: 'adv.', def: 'cũng, ngoài ra', us: '/ˈɔːlsoʊ/', uk: '/ˈɔːlsəʊ/' },
  { term: 'always', pos: 'adv.', def: 'luôn luôn', us: '/ˈɔːlweɪz/', uk: '/ˈɔːlweɪz/' },
  { term: 'amazing', pos: 'adj.', def: 'tuyệt vời, kinh ngạc', us: '/əˈmeɪzɪŋ/', uk: '/əˈmeɪzɪŋ/' },
  { term: 'and', pos: 'conj.', def: 'và', us: '/ænd/', uk: '/ænd/' },
  { term: 'angry', pos: 'adj.', def: 'tức giận, giận giữ', us: '/ˈæŋɡri/', uk: '/ˈæŋɡri/' },
  { term: 'animal', pos: 'n.', def: 'động vật, thú cưng', us: '/ˈænɪml/', uk: '/ˈænɪml/' },
  { term: 'another', pos: 'det., pron.', def: 'khác, một cái khác', us: '/əˈnʌðər/', uk: '/əˈnʌðə(r)/' },
  { term: 'answer', pos: 'n., v.', def: 'câu trả lời, trả lời', us: '/ˈænsər/', uk: '/ˈɑːnsə(r)/' },
  { term: 'any', pos: 'det., pron.', def: 'bất kỳ', us: '/ˈeni/', uk: '/ˈeni/' },
  { term: 'anyone', pos: 'pron.', def: 'bất kỳ ai', us: '/ˈeniwʌn/', uk: '/ˈeniwʌn/' },
  { term: 'anything', pos: 'pron.', def: 'bất kỳ điều gì', us: '/ˈeniθɪŋ/', uk: '/ˈeniθɪŋ/' },
  { term: 'apartment', pos: 'n.', def: 'căn hộ', us: '/əˈpɑːrtmənt/', uk: '/əˈpɑːtmənt/' },
  { term: 'apple', pos: 'n.', def: 'quả táo', us: '/ˈæpl/', uk: '/ˈæpl/' },
  { term: 'April', pos: 'n.', def: 'tháng Tư', us: '/ˈeɪprəl/', uk: '/ˈeɪprəl/' },
  { term: 'area', pos: 'n.', def: 'khu vực, diện tích', us: '/ˈeriə/', uk: '/ˈeəriə/' },
  { term: 'arm', pos: 'n.', def: 'cánh tay', us: '/ɑːrm/', uk: '/ɑːm/' },
  { term: 'around', pos: 'prep., adv.', def: 'xung quanh, khoảng', us: '/əˈraʊnd/', uk: '/əˈraʊnd/' },
  { term: 'arrive', pos: 'v.', def: 'đến, tới nơi', us: '/əˈraɪv/', uk: '/əˈraɪv/' },
  { term: 'art', pos: 'n.', def: 'nghệ thuật', us: '/ɑːrt/', uk: '/ɑːt/' },
  { term: 'article', pos: 'n.', def: 'bài báo, điều khoản', us: '/ˈɑːrtɪkl/', uk: '/ˈɑːtɪkl/' },
  { term: 'artist', pos: 'n.', def: 'nghệ sĩ, họa sĩ', us: '/ˈɑːrtɪst/', uk: '/ˈɑːtɪst/' },
  { term: 'as', pos: 'prep.', def: 'như là, khi, vì', us: '/æz/', uk: '/æz/' },
  { term: 'ask', pos: 'v.', def: 'hỏi, yêu cầu', us: '/æsk/', uk: '/ɑːsk/' },
  { term: 'at', pos: 'prep.', def: 'tại, ở', us: '/æt/', uk: '/æt/' },
  { term: 'August', pos: 'n.', def: 'tháng Tám', us: '/ˈɔːɡəst/', uk: '/ˈɔːɡəst/' },
  { term: 'aunt', pos: 'n.', def: 'cô, dì, bác gái', us: '/ænt/', uk: '/ɑːnt/' },
  { term: 'awesome', pos: 'adj.', def: 'tuyệt vời, đỉnh', us: '/ˈɔːsəm/', uk: '/ˈɔːsəm/' },
  { term: 'baby', pos: 'n.', def: 'em bé, trẻ sơ sinh', us: '/ˈbeɪbi/', uk: '/ˈbeɪbi/' },
  { term: 'back', pos: 'n., adv.', def: 'lưng, phía sau, trở lại', us: '/bæk/', uk: '/bæk/' },
  { term: 'bad', pos: 'adj.', def: 'tồi tệ, xấu, dở', us: '/bæd/', uk: '/bæd/' },
  { term: 'bag', pos: 'n.', def: 'túi, túi xách, cặp', us: '/bæɡ/', uk: '/bæɡ/' },
  { term: 'ball', pos: 'n.', def: 'quả bóng', us: '/bɔːl/', uk: '/bɔːl/' },
  { term: 'banana', pos: 'n.', def: 'quả chuối', us: '/bəˈnænə/', uk: '/bəˈnɑːnə/' },
  { term: 'band', pos: 'n.', def: 'ban nhạc', us: '/bænd/', uk: '/bænd/' },
  { term: 'bank', pos: 'n.', def: 'ngân hàng', us: '/bæŋk/', uk: '/bæŋk/' },
  { term: 'bar', pos: 'n.', def: 'quán bar, thanh', us: '/bɑːr/', uk: '/bɑː(r)/' },
  { term: 'baseball', pos: 'n.', def: 'bóng chày', us: '/ˈbeɪsbɔːl/', uk: '/ˈbeɪsbɔːl/' },
  { term: 'basketball', pos: 'n.', def: 'bóng rổ', us: '/ˈbæskɪtbɔːl/', uk: '/ˈbɑːskɪtbɔːl/' },
  { term: 'bath', pos: 'n.', def: 'việc tắm, bồn tắm', us: '/bæθ/', uk: '/bɑːθ/' },
  { term: 'bathroom', pos: 'n.', def: 'phòng tắm', us: '/ˈbæθruːm/', uk: '/ˈbɑːθruːm/' },
  { term: 'be', pos: 'v.', def: 'thì, là, ở', us: '/biː/', uk: '/biː/' },
  { term: 'beach', pos: 'n.', def: 'bãi biển', us: '/biːtʃ/', uk: '/biːtʃ/' },
  { term: 'beautiful', pos: 'adj.', def: 'đẹp, xinh đẹp', us: '/ˈbjuːtɪfl/', uk: '/ˈbjuːtɪfl/' },
  { term: 'because', pos: 'conj.', def: 'bởi vì', us: '/bɪˈkɔːz/', uk: '/bɪˈkɒz/' },
  { term: 'become', pos: 'v.', def: 'trở thành, trở nên', us: '/bɪˈkʌm/', uk: '/bɪˈkʌm/' },
  { term: 'bed', pos: 'n.', def: 'giường ngủ', us: '/bed/', uk: '/bed/' },
  { term: 'bedroom', pos: 'n.', def: 'phòng ngủ', us: '/ˈbedruːm/', uk: '/ˈbedruːm/' },
  { term: 'beer', pos: 'n.', def: 'bia', us: '/bɪr/', uk: '/bɪə(r)/' },
  { term: 'before', pos: 'prep.', def: 'trước, trước khi', us: '/bɪˈfɔːr/', uk: '/bɪˈfɔː(r)/' },
  { term: 'begin', pos: 'v.', def: 'bắt đầu', us: '/bɪˈɡɪn/', uk: '/bɪˈɡɪn/' },
  { term: 'beginning', pos: 'n.', def: 'sự bắt đầu, phần đầu', us: '/bɪˈɡɪnɪŋ/', uk: '/bɪˈɡɪnɪŋ/' },
  { term: 'behind', pos: 'prep., adv.', def: 'phía sau, đằng sau', us: '/bɪˈhaɪnd/', uk: '/bɪˈhaɪnd/' },
  { term: 'believe', pos: 'v.', def: 'tin tưởng, tin rằng', us: '/bɪˈliːv/', uk: '/bɪˈliːv/' },
  { term: 'below', pos: 'adv., prep.', def: 'ở dưới, bên dưới', us: '/bɪˈloʊ/', uk: '/bɪˈləʊ/' },
  { term: 'best', pos: 'adj., adv.', def: 'tốt nhất, giỏi nhất', us: '/best/', uk: '/best/' },
  { term: 'better', pos: 'adj., adv.', def: 'tốt hơn, khá hơn', us: '/ˈbetər/', uk: '/ˈbetə(r)/' },
  { term: 'between', pos: 'prep.', def: 'ở giữa', us: '/bɪˈtwiːn/', uk: '/bɪˈtwiːn/' },
  { term: 'bicycle', pos: 'n.', def: 'xe đạp', us: '/ˈbaɪsɪkl/', uk: '/ˈbaɪsɪkl/' },
  { term: 'big', pos: 'adj.', def: 'to, lớn', us: '/bɪɡ/', uk: '/bɪɡ/' },
  { term: 'bike', pos: 'n.', def: 'xe đạp', us: '/baɪk/', uk: '/baɪk/' },
  { term: 'bill', pos: 'n.', def: 'hóa đơn, tiền giấy', us: '/bɪl/', uk: '/bɪl/' },
  { term: 'bird', pos: 'n.', def: 'con chim', us: '/bɜːrd/', uk: '/bɜːd/' },
  { term: 'birthday', pos: 'n.', def: 'ngày sinh nhật', us: '/ˈbɜːrθdeɪ/', uk: '/ˈbɜːθdeɪ/' },
  { term: 'black', pos: 'adj., n.', def: 'màu đen', us: '/blæk/', uk: '/blæk/' },
  { term: 'blog', pos: 'n.', def: 'trang nhật ký mạng', us: '/blɑːɡ/', uk: '/blɒɡ/' },
  { term: 'blond', pos: 'adj.', def: 'tóc vàng', us: '/blɑːnd/', uk: '/blɒnd/' },
  { term: 'blue', pos: 'adj., n.', def: 'màu xanh dương', us: '/bluː/', uk: '/bluː/' },
  { term: 'board', pos: 'n.', def: 'tấm bảng, hội đồng', us: '/bɔːrd/', uk: '/bɔːd/' },
  { term: 'boat', pos: 'n.', def: 'con thuyền, tàu nhỏ', us: '/boʊt/', uk: '/bəʊt/' },
  { term: 'body', pos: 'n.', def: 'cơ thể, thân thể', us: '/ˈbɑːdi/', uk: '/ˈbɒdi/' },
  { term: 'book', pos: 'n.', def: 'cuốn sách', us: '/bʊk/', uk: '/bʊk/' },
  { term: 'boot', pos: 'n.', def: 'giày cao cổ, ủng', us: '/buːt/', uk: '/buːt/' },
  { term: 'bored', pos: 'adj.', def: 'chán nản, buồn chán', us: '/bɔːrd/', uk: '/bɔːd/' },
  { term: 'boring', pos: 'adj.', def: 'nhàm chán, tẻ nhạt', us: '/ˈbɔːrɪŋ/', uk: '/ˈbɔːrɪŋ/' },
  { term: 'born', pos: 'v.', def: 'sinh ra', us: '/bɔːrn/', uk: '/bɔːn/' },
  { term: 'both', pos: 'det., pron.', def: 'cả hai', us: '/boʊθ/', uk: '/bəʊθ/' },
  { term: 'bottle', pos: 'n.', def: 'cái chai, lọ', us: '/ˈbɑːtl/', uk: '/ˈbɒtl/' },
  { term: 'box', pos: 'n.', def: 'cái hộp, chiếc thùng', us: '/bɑːks/', uk: '/bɒks/' },
  { term: 'boy', pos: 'n.', def: 'cậu bé, con trai', us: '/bɔɪ/', uk: '/bɔɪ/' },
  { term: 'boyfriend', pos: 'n.', def: 'bạn trai', us: '/ˈbɔɪfrend/', uk: '/ˈbɔɪfrend/' },
  { term: 'bread', pos: 'n.', def: 'bánh mì', us: '/bred/', uk: '/bred/' },
  { term: 'break', pos: 'v., n.', def: 'làm gãy, vỡ; giờ giải lao', us: '/breɪk/', uk: '/breɪk/' },
  { term: 'breakfast', pos: 'n.', def: 'bữa ăn sáng', us: '/ˈbrekfəst/', uk: '/ˈbrekfəst/' },
  { term: 'bring', pos: 'v.', def: 'mang theo, mang lại', us: '/brɪŋ/', uk: '/brɪŋ/' },
  { term: 'brother', pos: 'n.', def: 'anh/em trai', us: '/ˈbrʌðər/', uk: '/ˈbrʌðə(r)/' },
  { term: 'brown', pos: 'adj., n.', def: 'màu nâu', us: '/braʊn/', uk: '/braʊn/' },
  { term: 'build', pos: 'v.', def: 'xây dựng', us: '/bɪld/', uk: '/bɪld/' },
  { term: 'building', pos: 'n.', def: 'tòa nhà, công trình', us: '/ˈbɪldɪŋ/', uk: '/ˈbɪldɪŋ/' },
  { term: 'bus', pos: 'n.', def: 'xe buýt', us: '/bʌs/', uk: '/bʌs/' },
  { term: 'business', pos: 'n.', def: 'doanh nghiệp, kinh doanh', us: '/ˈbɪznəs/', uk: '/ˈbɪznəs/' },
  { term: 'busy', pos: 'adj.', def: 'bận rộn', us: '/ˈbɪzi/', uk: '/ˈbɪzi/' },
  { term: 'but', pos: 'conj.', def: 'nhưng', us: '/bʌt/', uk: '/bʌt/' },
  { term: 'butter', pos: 'n.', def: 'bơ', us: '/ˈbʌtər/', uk: '/ˈbʌtə(r)/' },
  { term: 'buy', pos: 'v.', def: 'mua', us: '/baɪ/', uk: '/baɪ/' },
  { term: 'bye', pos: 'exclam.', def: 'tạm biệt', us: '/baɪ/', uk: '/baɪ/' },
  { term: 'cafe', pos: 'n.', def: 'quán cà phê', us: '/kæˈfeɪ/', uk: '/ˈkæfeɪ/' },
  { term: 'cake', pos: 'n.', def: 'bánh ngọt', us: '/keɪk/', uk: '/keɪk/' },
  { term: 'call', pos: 'v., n.', def: 'gọi điện, cuộc gọi', us: '/kɔːl/', uk: '/kɔːl/' },
  { term: 'camera', pos: 'n.', def: 'máy ảnh', us: '/ˈkæmrə/', uk: '/ˈkæmrə/' },
  { term: 'can', pos: 'modal v.', def: 'có thể', us: '/kæn/', uk: '/kæn/' },
  { term: 'cannot', pos: 'v.', def: 'không thể', us: '/ˈkænɑːt/', uk: '/ˈkænɒt/' },
  { term: 'capital', pos: 'n., adj.', def: 'thủ đô, chữ hoa', us: '/ˈkæpɪtl/', uk: '/ˈkæpɪtl/' },
  { term: 'car', pos: 'n.', def: 'ô tô, xe hơi', us: '/kɑːr/', uk: '/kɑː(r)/' },
  { term: 'card', pos: 'n.', def: 'thẻ, thiệp', us: '/kɑːrd/', uk: '/kɑːd/' },
  { term: 'career', pos: 'n.', def: 'sự nghiệp', us: '/kəˈrɪr/', uk: '/kəˈrɪə(r)/' },
  { term: 'carrot', pos: 'n.', def: 'củ cà rốt', us: '/ˈkærət/', uk: '/ˈkærət/' },
  { term: 'carry', pos: 'v.', def: 'mang, vác, gánh', us: '/ˈkæri/', uk: '/ˈkæri/' },
  { term: 'cat', pos: 'n.', def: 'con mèo', us: '/kæt/', uk: '/kæt/' },
  { term: 'CD', pos: 'n.', def: 'đĩa CD', us: '/ˌsiː ˈdiː/', uk: '/ˌsiː ˈdiː/' },
  { term: 'center', pos: 'n.', def: 'trung tâm', us: '/ˈsentər/', uk: '/ˈsentə(r)/' },
  { term: 'chair', pos: 'n.', def: 'cái ghế', us: '/tʃer/', uk: '/tʃeə(r)/' },
  { term: 'change', pos: 'v., n.', def: 'thay đổi, sự thay đổi', us: '/tʃeɪndʒ/', uk: '/tʃeɪndʒ/' },
  { term: 'cheap', pos: 'adj.', def: 'rẻ, giá rẻ', us: '/tʃiːp/', uk: '/tʃiːp/' },
  { term: 'check', pos: 'v.', def: 'kiểm tra', us: '/tʃek/', uk: '/tʃek/' },
  { term: 'cheese', pos: 'n.', def: 'pho mát', us: '/tʃiːz/', uk: '/tʃiːz/' },
  { term: 'chicken', pos: 'n.', def: 'con gà, thịt gà', us: '/ˈtʃɪkɪn/', uk: '/ˈtʃɪkɪn/' },
  { term: 'child', pos: 'n.', def: 'đứa trẻ, con cái', us: '/tʃaɪld/', uk: '/tʃaɪld/' },
  { term: 'chocolate', pos: 'n.', def: 'sô-cô-la', us: '/ˈtʃɑːklət/', uk: '/ˈtʃɒklət/' },
  { term: 'choose', pos: 'v.', def: 'chọn, lựa chọn', us: '/tʃuːz/', uk: '/tʃuːz/' },
  { term: 'city', pos: 'n.', def: 'thành phố', us: '/ˈsɪti/', uk: '/ˈsɪti/' },
  { term: 'class', pos: 'n.', def: 'lớp học, giai cấp', us: '/klæs/', uk: '/klɑːs/' },
  { term: 'classroom', pos: 'n.', def: 'phòng học', us: '/ˈklæsruːm/', uk: '/ˈklɑːsruːm/' },
  { term: 'clean', pos: 'adj., v.', def: 'sạch sẽ, lau dọn', us: '/kliːn/', uk: '/kliːn/' },
  { term: 'climb', pos: 'v.', def: 'leo trèo, leo núi', us: '/klaɪm/', uk: '/klaɪm/' },
  { term: 'clock', pos: 'n.', def: 'đồng hồ treo tường', us: '/klɑːk/', uk: '/klɒk/' },
  { term: 'close', pos: 'v.', def: 'đóng lại', us: '/kloʊz/', uk: '/kləʊz/' },
  { term: 'clothes', pos: 'n.', def: 'quần áo', us: '/kloʊðz/', uk: '/kləʊðz/' },
  { term: 'club', pos: 'n.', def: 'câu lạc bộ', us: '/klʌb/', uk: '/klʌb/' },
  { term: 'coat', pos: 'n.', def: 'áo khoác ngoài', us: '/koʊt/', uk: '/kəʊt/' },
  { term: 'coffee', pos: 'n.', def: 'cà phê', us: '/ˈkɔːfi/', uk: '/ˈkɒfi/' },
  { term: 'cold', pos: 'adj., n.', def: 'lạnh, sự cảm lạnh', us: '/koʊld/', uk: '/kləʊld/' },
  { term: 'college', pos: 'n.', def: 'trường đại học/cao đẳng', us: '/ˈkɑːlɪdʒ/', uk: '/ˈkɒlɪdʒ/' },
  { term: 'color', pos: 'n.', def: 'màu sắc', us: '/ˈkʌlər/', uk: '/ˈkʌlə(r)/' },
  { term: 'come', pos: 'v.', def: 'đến, tới', us: '/kʌm/', uk: '/kʌm/' },
  { term: 'common', pos: 'adj.', def: 'phổ biến, thông thường', us: '/ˈkɑːmən/', uk: '/ˈkɒmən/' },
  { term: 'company', pos: 'n.', def: 'công ty, sự đồng hành', us: '/ˈkʌmpəni/', uk: '/ˈkʌmpəni/' },
  { term: 'compare', pos: 'v.', def: 'so sánh', us: '/kəmˈper/', uk: '/kəmˈpeə(r)/' },
  { term: 'complete', pos: 'adj., v.', def: 'hoàn thành, đầy đủ', us: '/kəmˈpliːt/', uk: '/kəmˈpliːt/' },
  { term: 'computer', pos: 'n.', def: 'máy tính', us: '/kəmˈpjuːtər/', uk: '/kəmˈpjuːtə(r)/' },
  { term: 'concert', pos: 'n.', def: 'buổi hòa nhạc', us: '/ˈkɑːnsərt/', uk: '/ˈkɒnsət/' },
  { term: 'conversation', pos: 'n.', def: 'cuộc trò chuyện', us: '/ˌkɑːnvərˈseɪʃn/', uk: '/ˌkɒnvəˈseɪʃn/' },
  { term: 'cook', pos: 'v., n.', def: 'nấu ăn, đầu bếp', us: '/kʊk/', uk: '/kʊk/' },
  { term: 'cooking', pos: 'n.', def: 'việc nấu ăn', us: '/ˈkʊkɪŋ/', uk: '/ˈkʊkɪŋ/' },
  { term: 'cool', pos: 'adj.', def: 'mát mẻ, tuyệt vời', us: '/kuːl/', uk: '/kuːl/' },
  { term: 'correct', pos: 'adj., v.', def: 'đúng, sửa cho đúng', us: '/kəˈrekt/', uk: '/kəˈrekt/' },
  { term: 'cost', pos: 'n., v.', def: 'chi phí, có giá', us: '/kɑːst/', uk: '/kɒst/' },
  { term: 'country', pos: 'n.', def: 'quốc gia, nông thôn', us: '/ˈkʌntri/', uk: '/ˈkʌntri/' },
  { term: 'course', pos: 'n.', def: 'khóa học', us: '/kɔːrs/', uk: '/kɔːs/' },
  { term: 'cousin', pos: 'n.', def: 'anh chị em họ', us: '/ˈkʌzn/', uk: '/ˈkʌzn/' },
  { term: 'cow', pos: 'n.', def: 'con bò', us: '/kaʊ/', uk: '/kaʊ/' },
  { term: 'create', pos: 'v.', def: 'tạo ra, sáng tạo', us: '/kriˈeɪt/', uk: '/kriˈeɪt/' },
  { term: 'cross', pos: 'v., n.', def: 'băng qua; dấu thập', us: '/krɔːs/', uk: '/krɒs/' },
  { term: 'cry', pos: 'v., n.', def: 'khóc, tiếng khóc', us: '/kraɪ/', uk: '/kraɪ/' },
  { term: 'culture', pos: 'n.', def: 'văn hóa', us: '/ˈkʌltʃər/', uk: '/ˈkʌltʃə(r)/' },
  { term: 'cup', pos: 'n.', def: 'cái tách, chiếc cúp', us: '/kʌp/', uk: '/kʌp/' },
  { term: 'customer', pos: 'n.', def: 'khách hàng', us: '/ˈkʌstəmər/', uk: '/ˈkʌstəmə(r)/' },
  { term: 'cut', pos: 'v., n.', def: 'cắt, vết cắt', us: '/kʌt/', uk: '/kʌt/' }
];

let sql = `-- ====================================================\n`;
sql += `-- SQL SEED DATA: Oxford 3000 - Trình độ A1 (Tập mẫu 150 từ)\n`;
sql += `-- Bao gồm: Term, Part of Speech, CEFR Level, Definition, Phonetics (US & UK)\n`;
sql += `-- ====================================================\n\n`;
sql += `DO $$\nDECLARE\n    set_a1_id UUID;\nBEGIN\n`;
sql += `    -- 1. Tạo bộ học tập "Oxford 3000 - Trình độ A1" nếu chưa tồn tại\n`;
sql += `    SELECT id INTO set_a1_id FROM public.sets WHERE title = 'Oxford 3000 - Trình độ A1' LIMIT 1;\n\n`;
sql += `    IF set_a1_id IS NULL THEN\n`;
sql += `        INSERT INTO public.sets (id, title, description, is_public)\n`;
sql += `        VALUES (gen_random_uuid(), 'Oxford 3000 - Trình độ A1', 'Bộ từ vựng tiếng Anh căn bản nhất cấp độ A1 theo từ điển Oxford 3000', true)\n`;
sql += `        RETURNING id INTO set_a1_id;\n`;
sql += `    END IF;\n\n`;
sql += `    -- 2. Thêm danh sách thẻ ghi nhớ (Cards) kèm phiên âm UK & US\n`;
sql += `    INSERT INTO public.cards (set_id, term, part_of_speech, cefr_level, definition, phonetic, phonetic_uk, order_index)\n`;
sql += `    VALUES\n`;

const values = a1Words.map((w, index) => {
  const termEsc = w.term.replace(/'/g, "''");
  const posEsc = w.pos.replace(/'/g, "''");
  const defEsc = w.def.replace(/'/g, "''");
  const usEsc = w.us.replace(/'/g, "''");
  const ukEsc = w.uk.replace(/'/g, "''");
  return `        (set_a1_id, '${termEsc}', '${posEsc}', 'A1', '${defEsc}', '${usEsc}', '${ukEsc}', ${index + 1})`;
});

sql += values.join(',\n') + ';\n';
sql += `END $$;\n`;

fs.writeFileSync(path.join(__dirname, 'oxford_3000_a1.sql'), sql, 'utf8');
console.log(`Successfully generated oxford_3000_a1.sql with ${a1Words.length} words!`);
