-- ====================================================
-- SQL SEED DATA: Oxford 3000 - Trình độ A1 (Tập mẫu 150 từ)
-- Bao gồm: Term, Part of Speech, CEFR Level, Definition, Phonetics (US & UK)
-- ====================================================

DO $$
DECLARE
    set_a1_id UUID;
BEGIN
    -- 1. Tạo bộ học tập "Oxford 3000 - Trình độ A1" nếu chưa tồn tại
    SELECT id INTO set_a1_id FROM public.sets WHERE title = 'Oxford 3000 - Trình độ A1' LIMIT 1;

    IF set_a1_id IS NULL THEN
        INSERT INTO public.sets (id, title, description, is_public)
        VALUES (gen_random_uuid(), 'Oxford 3000 - Trình độ A1', 'Bộ từ vựng tiếng Anh căn bản nhất cấp độ A1 theo từ điển Oxford 3000', true)
        RETURNING id INTO set_a1_id;
    END IF;

    -- 2. Thêm danh sách thẻ ghi nhớ (Cards) kèm phiên âm UK & US
    INSERT INTO public.cards (set_id, term, part_of_speech, cefr_level, definition, phonetic, phonetic_uk, order_index)
    VALUES
        (set_a1_id, 'a, an', 'indefinite article', 'A1', 'một', '/ə/, /æn/', '/ə/, /æn/', 1),
        (set_a1_id, 'about', 'prep., adv.', 'A1', 'về, khoảng', '/əˈbaʊt/', '/əˈbaʊt/', 2),
        (set_a1_id, 'above', 'prep., adv.', 'A1', 'ở trên, phía trên', '/əˈbʌv/', '/əˈbʌv/', 3),
        (set_a1_id, 'across', 'prep., adv.', 'A1', 'băng qua, qua', '/əˈkrɔːs/', '/əˈkrɒs/', 4),
        (set_a1_id, 'action', 'n.', 'A1', 'hành động', '/ˈækʃn/', '/ˈækʃn/', 5),
        (set_a1_id, 'activity', 'n.', 'A1', 'hoạt động', '/ækˈtɪvəti/', '/ækˈtɪvəti/', 6),
        (set_a1_id, 'actor', 'n.', 'A1', 'nam diễn viên', '/ˈæktər/', '/ˈæktə(r)/', 7),
        (set_a1_id, 'actress', 'n.', 'A1', 'nữ diễn viên', '/ˈæktrəs/', '/ˈæktrəs/', 8),
        (set_a1_id, 'add', 'v.', 'A1', 'thêm vào, cộng', '/æd/', '/æd/', 9),
        (set_a1_id, 'address', 'n.', 'A1', 'địa chỉ', '/ˈædres/', '/əˈdres/', 10),
        (set_a1_id, 'adult', 'n.', 'A1', 'người trưởng thành', '/əˈdʌlt/', '/ˈædʌlt/', 11),
        (set_a1_id, 'afraid', 'adj.', 'A1', 'sợ hãi, lo sợ', '/əˈfreɪd/', '/əˈfreɪd/', 12),
        (set_a1_id, 'after', 'prep.', 'A1', 'sau, sau khi', '/ˈæftər/', '/ˈɑːftə(r)/', 13),
        (set_a1_id, 'afternoon', 'n.', 'A1', 'buổi chiều', '/ˌæftərˈnuːn/', '/ˌɑːftəˈnuːn/', 14),
        (set_a1_id, 'again', 'adv.', 'A1', 'lại, một lần nữa', '/əˈɡen/', '/əˈɡen/', 15),
        (set_a1_id, 'age', 'n.', 'A1', 'tuổi, tuổi tác', '/eɪdʒ/', '/eɪdʒ/', 16),
        (set_a1_id, 'ago', 'adv.', 'A1', 'trước đây, cách đây', '/əˈɡoʊ/', '/əˈɡəʊ/', 17),
        (set_a1_id, 'agree', 'v.', 'A1', 'đồng ý', '/əˈɡriː/', '/əˈɡriː/', 18),
        (set_a1_id, 'air', 'n.', 'A1', 'không khí', '/er/', '/eə(r)/', 19),
        (set_a1_id, 'airport', 'n.', 'A1', 'sân bay', '/ˈerpɔːrt/', '/ˈeəpɔːt/', 20),
        (set_a1_id, 'all', 'det., pron.', 'A1', 'tất cả', '/ɔːl/', '/ɔːl/', 21),
        (set_a1_id, 'also', 'adv.', 'A1', 'cũng, ngoài ra', '/ˈɔːlsoʊ/', '/ˈɔːlsəʊ/', 22),
        (set_a1_id, 'always', 'adv.', 'A1', 'luôn luôn', '/ˈɔːlweɪz/', '/ˈɔːlweɪz/', 23),
        (set_a1_id, 'amazing', 'adj.', 'A1', 'tuyệt vời, kinh ngạc', '/əˈmeɪzɪŋ/', '/əˈmeɪzɪŋ/', 24),
        (set_a1_id, 'and', 'conj.', 'A1', 'và', '/ænd/', '/ænd/', 25),
        (set_a1_id, 'angry', 'adj.', 'A1', 'tức giận, giận giữ', '/ˈæŋɡri/', '/ˈæŋɡri/', 26),
        (set_a1_id, 'animal', 'n.', 'A1', 'động vật, thú cưng', '/ˈænɪml/', '/ˈænɪml/', 27),
        (set_a1_id, 'another', 'det., pron.', 'A1', 'khác, một cái khác', '/əˈnʌðər/', '/əˈnʌðə(r)/', 28),
        (set_a1_id, 'answer', 'n., v.', 'A1', 'câu trả lời, trả lời', '/ˈænsər/', '/ˈɑːnsə(r)/', 29),
        (set_a1_id, 'any', 'det., pron.', 'A1', 'bất kỳ', '/ˈeni/', '/ˈeni/', 30),
        (set_a1_id, 'anyone', 'pron.', 'A1', 'bất kỳ ai', '/ˈeniwʌn/', '/ˈeniwʌn/', 31),
        (set_a1_id, 'anything', 'pron.', 'A1', 'bất kỳ điều gì', '/ˈeniθɪŋ/', '/ˈeniθɪŋ/', 32),
        (set_a1_id, 'apartment', 'n.', 'A1', 'căn hộ', '/əˈpɑːrtmənt/', '/əˈpɑːtmənt/', 33),
        (set_a1_id, 'apple', 'n.', 'A1', 'quả táo', '/ˈæpl/', '/ˈæpl/', 34),
        (set_a1_id, 'April', 'n.', 'A1', 'tháng Tư', '/ˈeɪprəl/', '/ˈeɪprəl/', 35),
        (set_a1_id, 'area', 'n.', 'A1', 'khu vực, diện tích', '/ˈeriə/', '/ˈeəriə/', 36),
        (set_a1_id, 'arm', 'n.', 'A1', 'cánh tay', '/ɑːrm/', '/ɑːm/', 37),
        (set_a1_id, 'around', 'prep., adv.', 'A1', 'xung quanh, khoảng', '/əˈraʊnd/', '/əˈraʊnd/', 38),
        (set_a1_id, 'arrive', 'v.', 'A1', 'đến, tới nơi', '/əˈraɪv/', '/əˈraɪv/', 39),
        (set_a1_id, 'art', 'n.', 'A1', 'nghệ thuật', '/ɑːrt/', '/ɑːt/', 40),
        (set_a1_id, 'article', 'n.', 'A1', 'bài báo, điều khoản', '/ˈɑːrtɪkl/', '/ˈɑːtɪkl/', 41),
        (set_a1_id, 'artist', 'n.', 'A1', 'nghệ sĩ, họa sĩ', '/ˈɑːrtɪst/', '/ˈɑːtɪst/', 42),
        (set_a1_id, 'as', 'prep.', 'A1', 'như là, khi, vì', '/æz/', '/æz/', 43),
        (set_a1_id, 'ask', 'v.', 'A1', 'hỏi, yêu cầu', '/æsk/', '/ɑːsk/', 44),
        (set_a1_id, 'at', 'prep.', 'A1', 'tại, ở', '/æt/', '/æt/', 45),
        (set_a1_id, 'August', 'n.', 'A1', 'tháng Tám', '/ˈɔːɡəst/', '/ˈɔːɡəst/', 46),
        (set_a1_id, 'aunt', 'n.', 'A1', 'cô, dì, bác gái', '/ænt/', '/ɑːnt/', 47),
        (set_a1_id, 'awesome', 'adj.', 'A1', 'tuyệt vời, đỉnh', '/ˈɔːsəm/', '/ˈɔːsəm/', 48),
        (set_a1_id, 'baby', 'n.', 'A1', 'em bé, trẻ sơ sinh', '/ˈbeɪbi/', '/ˈbeɪbi/', 49),
        (set_a1_id, 'back', 'n., adv.', 'A1', 'lưng, phía sau, trở lại', '/bæk/', '/bæk/', 50),
        (set_a1_id, 'bad', 'adj.', 'A1', 'tồi tệ, xấu, dở', '/bæd/', '/bæd/', 51),
        (set_a1_id, 'bag', 'n.', 'A1', 'túi, túi xách, cặp', '/bæɡ/', '/bæɡ/', 52),
        (set_a1_id, 'ball', 'n.', 'A1', 'quả bóng', '/bɔːl/', '/bɔːl/', 53),
        (set_a1_id, 'banana', 'n.', 'A1', 'quả chuối', '/bəˈnænə/', '/bəˈnɑːnə/', 54),
        (set_a1_id, 'band', 'n.', 'A1', 'ban nhạc', '/bænd/', '/bænd/', 55),
        (set_a1_id, 'bank', 'n.', 'A1', 'ngân hàng', '/bæŋk/', '/bæŋk/', 56),
        (set_a1_id, 'bar', 'n.', 'A1', 'quán bar, thanh', '/bɑːr/', '/bɑː(r)/', 57),
        (set_a1_id, 'baseball', 'n.', 'A1', 'bóng chày', '/ˈbeɪsbɔːl/', '/ˈbeɪsbɔːl/', 58),
        (set_a1_id, 'basketball', 'n.', 'A1', 'bóng rổ', '/ˈbæskɪtbɔːl/', '/ˈbɑːskɪtbɔːl/', 59),
        (set_a1_id, 'bath', 'n.', 'A1', 'việc tắm, bồn tắm', '/bæθ/', '/bɑːθ/', 60),
        (set_a1_id, 'bathroom', 'n.', 'A1', 'phòng tắm', '/ˈbæθruːm/', '/ˈbɑːθruːm/', 61),
        (set_a1_id, 'be', 'v.', 'A1', 'thì, là, ở', '/biː/', '/biː/', 62),
        (set_a1_id, 'beach', 'n.', 'A1', 'bãi biển', '/biːtʃ/', '/biːtʃ/', 63),
        (set_a1_id, 'beautiful', 'adj.', 'A1', 'đẹp, xinh đẹp', '/ˈbjuːtɪfl/', '/ˈbjuːtɪfl/', 64),
        (set_a1_id, 'because', 'conj.', 'A1', 'bởi vì', '/bɪˈkɔːz/', '/bɪˈkɒz/', 65),
        (set_a1_id, 'become', 'v.', 'A1', 'trở thành, trở nên', '/bɪˈkʌm/', '/bɪˈkʌm/', 66),
        (set_a1_id, 'bed', 'n.', 'A1', 'giường ngủ', '/bed/', '/bed/', 67),
        (set_a1_id, 'bedroom', 'n.', 'A1', 'phòng ngủ', '/ˈbedruːm/', '/ˈbedruːm/', 68),
        (set_a1_id, 'beer', 'n.', 'A1', 'bia', '/bɪr/', '/bɪə(r)/', 69),
        (set_a1_id, 'before', 'prep.', 'A1', 'trước, trước khi', '/bɪˈfɔːr/', '/bɪˈfɔː(r)/', 70),
        (set_a1_id, 'begin', 'v.', 'A1', 'bắt đầu', '/bɪˈɡɪn/', '/bɪˈɡɪn/', 71),
        (set_a1_id, 'beginning', 'n.', 'A1', 'sự bắt đầu, phần đầu', '/bɪˈɡɪnɪŋ/', '/bɪˈɡɪnɪŋ/', 72),
        (set_a1_id, 'behind', 'prep., adv.', 'A1', 'phía sau, đằng sau', '/bɪˈhaɪnd/', '/bɪˈhaɪnd/', 73),
        (set_a1_id, 'believe', 'v.', 'A1', 'tin tưởng, tin rằng', '/bɪˈliːv/', '/bɪˈliːv/', 74),
        (set_a1_id, 'below', 'adv., prep.', 'A1', 'ở dưới, bên dưới', '/bɪˈloʊ/', '/bɪˈləʊ/', 75),
        (set_a1_id, 'best', 'adj., adv.', 'A1', 'tốt nhất, giỏi nhất', '/best/', '/best/', 76),
        (set_a1_id, 'better', 'adj., adv.', 'A1', 'tốt hơn, khá hơn', '/ˈbetər/', '/ˈbetə(r)/', 77),
        (set_a1_id, 'between', 'prep.', 'A1', 'ở giữa', '/bɪˈtwiːn/', '/bɪˈtwiːn/', 78),
        (set_a1_id, 'bicycle', 'n.', 'A1', 'xe đạp', '/ˈbaɪsɪkl/', '/ˈbaɪsɪkl/', 79),
        (set_a1_id, 'big', 'adj.', 'A1', 'to, lớn', '/bɪɡ/', '/bɪɡ/', 80),
        (set_a1_id, 'bike', 'n.', 'A1', 'xe đạp', '/baɪk/', '/baɪk/', 81),
        (set_a1_id, 'bill', 'n.', 'A1', 'hóa đơn, tiền giấy', '/bɪl/', '/bɪl/', 82),
        (set_a1_id, 'bird', 'n.', 'A1', 'con chim', '/bɜːrd/', '/bɜːd/', 83),
        (set_a1_id, 'birthday', 'n.', 'A1', 'ngày sinh nhật', '/ˈbɜːrθdeɪ/', '/ˈbɜːθdeɪ/', 84),
        (set_a1_id, 'black', 'adj., n.', 'A1', 'màu đen', '/blæk/', '/blæk/', 85),
        (set_a1_id, 'blog', 'n.', 'A1', 'trang nhật ký mạng', '/blɑːɡ/', '/blɒɡ/', 86),
        (set_a1_id, 'blond', 'adj.', 'A1', 'tóc vàng', '/blɑːnd/', '/blɒnd/', 87),
        (set_a1_id, 'blue', 'adj., n.', 'A1', 'màu xanh dương', '/bluː/', '/bluː/', 88),
        (set_a1_id, 'board', 'n.', 'A1', 'tấm bảng, hội đồng', '/bɔːrd/', '/bɔːd/', 89),
        (set_a1_id, 'boat', 'n.', 'A1', 'con thuyền, tàu nhỏ', '/boʊt/', '/bəʊt/', 90),
        (set_a1_id, 'body', 'n.', 'A1', 'cơ thể, thân thể', '/ˈbɑːdi/', '/ˈbɒdi/', 91),
        (set_a1_id, 'book', 'n.', 'A1', 'cuốn sách', '/bʊk/', '/bʊk/', 92),
        (set_a1_id, 'boot', 'n.', 'A1', 'giày cao cổ, ủng', '/buːt/', '/buːt/', 93),
        (set_a1_id, 'bored', 'adj.', 'A1', 'chán nản, buồn chán', '/bɔːrd/', '/bɔːd/', 94),
        (set_a1_id, 'boring', 'adj.', 'A1', 'nhàm chán, tẻ nhạt', '/ˈbɔːrɪŋ/', '/ˈbɔːrɪŋ/', 95),
        (set_a1_id, 'born', 'v.', 'A1', 'sinh ra', '/bɔːrn/', '/bɔːn/', 96),
        (set_a1_id, 'both', 'det., pron.', 'A1', 'cả hai', '/boʊθ/', '/bəʊθ/', 97),
        (set_a1_id, 'bottle', 'n.', 'A1', 'cái chai, lọ', '/ˈbɑːtl/', '/ˈbɒtl/', 98),
        (set_a1_id, 'box', 'n.', 'A1', 'cái hộp, chiếc thùng', '/bɑːks/', '/bɒks/', 99),
        (set_a1_id, 'boy', 'n.', 'A1', 'cậu bé, con trai', '/bɔɪ/', '/bɔɪ/', 100),
        (set_a1_id, 'boyfriend', 'n.', 'A1', 'bạn trai', '/ˈbɔɪfrend/', '/ˈbɔɪfrend/', 101),
        (set_a1_id, 'bread', 'n.', 'A1', 'bánh mì', '/bred/', '/bred/', 102),
        (set_a1_id, 'break', 'v., n.', 'A1', 'làm gãy, vỡ; giờ giải lao', '/breɪk/', '/breɪk/', 103),
        (set_a1_id, 'breakfast', 'n.', 'A1', 'bữa ăn sáng', '/ˈbrekfəst/', '/ˈbrekfəst/', 104),
        (set_a1_id, 'bring', 'v.', 'A1', 'mang theo, mang lại', '/brɪŋ/', '/brɪŋ/', 105),
        (set_a1_id, 'brother', 'n.', 'A1', 'anh/em trai', '/ˈbrʌðər/', '/ˈbrʌðə(r)/', 106),
        (set_a1_id, 'brown', 'adj., n.', 'A1', 'màu nâu', '/braʊn/', '/braʊn/', 107),
        (set_a1_id, 'build', 'v.', 'A1', 'xây dựng', '/bɪld/', '/bɪld/', 108),
        (set_a1_id, 'building', 'n.', 'A1', 'tòa nhà, công trình', '/ˈbɪldɪŋ/', '/ˈbɪldɪŋ/', 109),
        (set_a1_id, 'bus', 'n.', 'A1', 'xe buýt', '/bʌs/', '/bʌs/', 110),
        (set_a1_id, 'business', 'n.', 'A1', 'doanh nghiệp, kinh doanh', '/ˈbɪznəs/', '/ˈbɪznəs/', 111),
        (set_a1_id, 'busy', 'adj.', 'A1', 'bận rộn', '/ˈbɪzi/', '/ˈbɪzi/', 112),
        (set_a1_id, 'but', 'conj.', 'A1', 'nhưng', '/bʌt/', '/bʌt/', 113),
        (set_a1_id, 'butter', 'n.', 'A1', 'bơ', '/ˈbʌtər/', '/ˈbʌtə(r)/', 114),
        (set_a1_id, 'buy', 'v.', 'A1', 'mua', '/baɪ/', '/baɪ/', 115),
        (set_a1_id, 'bye', 'exclam.', 'A1', 'tạm biệt', '/baɪ/', '/baɪ/', 116),
        (set_a1_id, 'cafe', 'n.', 'A1', 'quán cà phê', '/kæˈfeɪ/', '/ˈkæfeɪ/', 117),
        (set_a1_id, 'cake', 'n.', 'A1', 'bánh ngọt', '/keɪk/', '/keɪk/', 118),
        (set_a1_id, 'call', 'v., n.', 'A1', 'gọi điện, cuộc gọi', '/kɔːl/', '/kɔːl/', 119),
        (set_a1_id, 'camera', 'n.', 'A1', 'máy ảnh', '/ˈkæmrə/', '/ˈkæmrə/', 120),
        (set_a1_id, 'can', 'modal v.', 'A1', 'có thể', '/kæn/', '/kæn/', 121),
        (set_a1_id, 'cannot', 'v.', 'A1', 'không thể', '/ˈkænɑːt/', '/ˈkænɒt/', 122),
        (set_a1_id, 'capital', 'n., adj.', 'A1', 'thủ đô, chữ hoa', '/ˈkæpɪtl/', '/ˈkæpɪtl/', 123),
        (set_a1_id, 'car', 'n.', 'A1', 'ô tô, xe hơi', '/kɑːr/', '/kɑː(r)/', 124),
        (set_a1_id, 'card', 'n.', 'A1', 'thẻ, thiệp', '/kɑːrd/', '/kɑːd/', 125),
        (set_a1_id, 'career', 'n.', 'A1', 'sự nghiệp', '/kəˈrɪr/', '/kəˈrɪə(r)/', 126),
        (set_a1_id, 'carrot', 'n.', 'A1', 'củ cà rốt', '/ˈkærət/', '/ˈkærət/', 127),
        (set_a1_id, 'carry', 'v.', 'A1', 'mang, vác, gánh', '/ˈkæri/', '/ˈkæri/', 128),
        (set_a1_id, 'cat', 'n.', 'A1', 'con mèo', '/kæt/', '/kæt/', 129),
        (set_a1_id, 'CD', 'n.', 'A1', 'đĩa CD', '/ˌsiː ˈdiː/', '/ˌsiː ˈdiː/', 130),
        (set_a1_id, 'center', 'n.', 'A1', 'trung tâm', '/ˈsentər/', '/ˈsentə(r)/', 131),
        (set_a1_id, 'chair', 'n.', 'A1', 'cái ghế', '/tʃer/', '/tʃeə(r)/', 132),
        (set_a1_id, 'change', 'v., n.', 'A1', 'thay đổi, sự thay đổi', '/tʃeɪndʒ/', '/tʃeɪndʒ/', 133),
        (set_a1_id, 'cheap', 'adj.', 'A1', 'rẻ, giá rẻ', '/tʃiːp/', '/tʃiːp/', 134),
        (set_a1_id, 'check', 'v.', 'A1', 'kiểm tra', '/tʃek/', '/tʃek/', 135),
        (set_a1_id, 'cheese', 'n.', 'A1', 'pho mát', '/tʃiːz/', '/tʃiːz/', 136),
        (set_a1_id, 'chicken', 'n.', 'A1', 'con gà, thịt gà', '/ˈtʃɪkɪn/', '/ˈtʃɪkɪn/', 137),
        (set_a1_id, 'child', 'n.', 'A1', 'đứa trẻ, con cái', '/tʃaɪld/', '/tʃaɪld/', 138),
        (set_a1_id, 'chocolate', 'n.', 'A1', 'sô-cô-la', '/ˈtʃɑːklət/', '/ˈtʃɒklət/', 139),
        (set_a1_id, 'choose', 'v.', 'A1', 'chọn, lựa chọn', '/tʃuːz/', '/tʃuːz/', 140),
        (set_a1_id, 'city', 'n.', 'A1', 'thành phố', '/ˈsɪti/', '/ˈsɪti/', 141),
        (set_a1_id, 'class', 'n.', 'A1', 'lớp học, giai cấp', '/klæs/', '/klɑːs/', 142),
        (set_a1_id, 'classroom', 'n.', 'A1', 'phòng học', '/ˈklæsruːm/', '/ˈklɑːsruːm/', 143),
        (set_a1_id, 'clean', 'adj., v.', 'A1', 'sạch sẽ, lau dọn', '/kliːn/', '/kliːn/', 144),
        (set_a1_id, 'climb', 'v.', 'A1', 'leo trèo, leo núi', '/klaɪm/', '/klaɪm/', 145),
        (set_a1_id, 'clock', 'n.', 'A1', 'đồng hồ treo tường', '/klɑːk/', '/klɒk/', 146),
        (set_a1_id, 'close', 'v.', 'A1', 'đóng lại', '/kloʊz/', '/kləʊz/', 147),
        (set_a1_id, 'clothes', 'n.', 'A1', 'quần áo', '/kloʊðz/', '/kləʊðz/', 148),
        (set_a1_id, 'club', 'n.', 'A1', 'câu lạc bộ', '/klʌb/', '/klʌb/', 149),
        (set_a1_id, 'coat', 'n.', 'A1', 'áo khoác ngoài', '/koʊt/', '/kəʊt/', 150),
        (set_a1_id, 'coffee', 'n.', 'A1', 'cà phê', '/ˈkɔːfi/', '/ˈkɒfi/', 151),
        (set_a1_id, 'cold', 'adj., n.', 'A1', 'lạnh, sự cảm lạnh', '/koʊld/', '/kləʊld/', 152),
        (set_a1_id, 'college', 'n.', 'A1', 'trường đại học/cao đẳng', '/ˈkɑːlɪdʒ/', '/ˈkɒlɪdʒ/', 153),
        (set_a1_id, 'color', 'n.', 'A1', 'màu sắc', '/ˈkʌlər/', '/ˈkʌlə(r)/', 154),
        (set_a1_id, 'come', 'v.', 'A1', 'đến, tới', '/kʌm/', '/kʌm/', 155),
        (set_a1_id, 'common', 'adj.', 'A1', 'phổ biến, thông thường', '/ˈkɑːmən/', '/ˈkɒmən/', 156),
        (set_a1_id, 'company', 'n.', 'A1', 'công ty, sự đồng hành', '/ˈkʌmpəni/', '/ˈkʌmpəni/', 157),
        (set_a1_id, 'compare', 'v.', 'A1', 'so sánh', '/kəmˈper/', '/kəmˈpeə(r)/', 158),
        (set_a1_id, 'complete', 'adj., v.', 'A1', 'hoàn thành, đầy đủ', '/kəmˈpliːt/', '/kəmˈpliːt/', 159),
        (set_a1_id, 'computer', 'n.', 'A1', 'máy tính', '/kəmˈpjuːtər/', '/kəmˈpjuːtə(r)/', 160),
        (set_a1_id, 'concert', 'n.', 'A1', 'buổi hòa nhạc', '/ˈkɑːnsərt/', '/ˈkɒnsət/', 161),
        (set_a1_id, 'conversation', 'n.', 'A1', 'cuộc trò chuyện', '/ˌkɑːnvərˈseɪʃn/', '/ˌkɒnvəˈseɪʃn/', 162),
        (set_a1_id, 'cook', 'v., n.', 'A1', 'nấu ăn, đầu bếp', '/kʊk/', '/kʊk/', 163),
        (set_a1_id, 'cooking', 'n.', 'A1', 'việc nấu ăn', '/ˈkʊkɪŋ/', '/ˈkʊkɪŋ/', 164),
        (set_a1_id, 'cool', 'adj.', 'A1', 'mát mẻ, tuyệt vời', '/kuːl/', '/kuːl/', 165),
        (set_a1_id, 'correct', 'adj., v.', 'A1', 'đúng, sửa cho đúng', '/kəˈrekt/', '/kəˈrekt/', 166),
        (set_a1_id, 'cost', 'n., v.', 'A1', 'chi phí, có giá', '/kɑːst/', '/kɒst/', 167),
        (set_a1_id, 'country', 'n.', 'A1', 'quốc gia, nông thôn', '/ˈkʌntri/', '/ˈkʌntri/', 168),
        (set_a1_id, 'course', 'n.', 'A1', 'khóa học', '/kɔːrs/', '/kɔːs/', 169),
        (set_a1_id, 'cousin', 'n.', 'A1', 'anh chị em họ', '/ˈkʌzn/', '/ˈkʌzn/', 170),
        (set_a1_id, 'cow', 'n.', 'A1', 'con bò', '/kaʊ/', '/kaʊ/', 171),
        (set_a1_id, 'create', 'v.', 'A1', 'tạo ra, sáng tạo', '/kriˈeɪt/', '/kriˈeɪt/', 172),
        (set_a1_id, 'cross', 'v., n.', 'A1', 'băng qua; dấu thập', '/krɔːs/', '/krɒs/', 173),
        (set_a1_id, 'cry', 'v., n.', 'A1', 'khóc, tiếng khóc', '/kraɪ/', '/kraɪ/', 174),
        (set_a1_id, 'culture', 'n.', 'A1', 'văn hóa', '/ˈkʌltʃər/', '/ˈkʌltʃə(r)/', 175),
        (set_a1_id, 'cup', 'n.', 'A1', 'cái tách, chiếc cúp', '/kʌp/', '/kʌp/', 176),
        (set_a1_id, 'customer', 'n.', 'A1', 'khách hàng', '/ˈkʌstəmər/', '/ˈkʌstəmə(r)/', 177),
        (set_a1_id, 'cut', 'v., n.', 'A1', 'cắt, vết cắt', '/kʌt/', '/kʌt/', 178);
END $$;
